# This file is part of the dune-grid-multiscale project:
#   http://users.dune-project.org/projects/dune-grid-multiscale
# Copyright holders: Felix Albrecht
# License: BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)

Module: dune-grid-multiscale
Version: 0.1
Maintainer: felix.schindler@wwu.de
Depends: dune-common (>= 2.4) dune-grid (>= 2.4) dune-xt-grid (>= 2.4)
Suggests: dune-alugrid dune-fem dune-grid-glue

